### ISSUE TITLE
Integrate requirement class (stubs) into code-base

### ISSUE THREAD

**Issue by waynewee** [AY1920S2-CS2103T-F09-3/main#87] opened 2020-03-07 08:00 UTC

**Comment by yjskrs** [comment] 2020-03-13 03:02
Er @nathanaelseen why you close

**Comment by nathanaelseen** [comment] 2020-03-13 03:04
sry I was confused, I thought this was a duplicate of this issue; `Support Requirement Commands (add, modify, delete) #91`, so I closed it

**Comment by nathanaelseen** [comment] 2020-03-13 03:27
@yjskrs could you rename this, I don't understand this task

**Comment by yjskrs** [comment] 2020-03-13 03:29
I'm just making a class without adding the commands and methods

**Comment by nathanaelseen** [comment] 2020-03-13 04:37
ok can, I'll just rename to 'Integrate requirement class (stubs) into code-base'

**Comment by nathanaelseen** [comment] 2020-03-16 07:43
I'll close this when I've finished merging the PR, sry for the delays!

**Closed as completed** 2020-03-16 17:31 UTC
Labels: priority.High, type.Coding
